/**
 * export-fast.mjs — 快速导出：WebCodecs 硬编码 + mediabunny 封装
 * 逐帧离屏渲染 → source.add(timestamp, duration)，速度=编码速度（通常 5~20× 实时）
 * 背景由 bg 描述（{ color } 纯色 / { image } 图片 cover 铺满 / 缺省透明）
 */
import {
  Output, Mp4OutputFormat, WebMOutputFormat, BufferTarget,
  CanvasSource, AudioBufferSource,
} from "./vendor.mediabunny.mjs";

const DEFAULT_VIDEO_BITRATE = 8_000_000;
const AUDIO_BITRATE = 96_000;

/**
 * 离屏快速导出（浏览器端调用，Node 无 WebCodecs 时会抛错）
 * opts: { imgs, analysis, fps, width, height, imageWidth, imageHeight, padding,
 *         audioBuffer, audioStart, audioEnd,
 *         frameStart, frameEnd, format: "webm"|"mp4",
 *         bg: { color?: string, image?: HTMLImageElement|null }, signal, onProgress }
 */
export async function exportFast(opts) {
  const { imgs, analysis, audioBuffer, format, bg, onProgress } = opts;
  const fps = opts.fps, W = opts.width, H = opts.height;
  const imageWidth = Number(opts.imageWidth), imageHeight = Number(opts.imageHeight), padding = Number(opts.padding);
  const frameStart = Number.isInteger(opts.frameStart) ? opts.frameStart : 0;
  const frameEnd = Number.isInteger(opts.frameEnd) ? opts.frameEnd : analysis.nframes;
  const n = frameEnd - frameStart;
  if (!Number.isInteger(frameStart) || !Number.isInteger(frameEnd) || frameStart < 0 || frameEnd > analysis.nframes || n <= 0) {
    throw new RangeError("导出帧范围无效");
  }
  throwIfAborted(opts.signal);

  const cv = new OffscreenCanvas(W, H);
  const ctx = cv.getContext("2d");

  const isMp4 = format === "mp4";
  const videoBitrate = Number.isFinite(opts.videoBitrate) && opts.videoBitrate > 0
    ? Math.round(opts.videoBitrate)
    : DEFAULT_VIDEO_BITRATE;
  const output = new Output({
    format: isMp4 ? new Mp4OutputFormat({ fastStart: "in-memory" }) : new WebMOutputFormat(),
    target: new BufferTarget(),
  });
  output.setMetadataTags({
    title: "lip-sync-web",
    comment: "Generated by lip-sync-web",
  });

  const videoSource = new CanvasSource(cv, {
    codec: isMp4 ? "avc" : "vp9",
    bitrate: videoBitrate,
  });
  const videoTrack = await output.addVideoTrack(videoSource, { frameRate: fps });

  let audioSource = null, audioTrack = null;
  if (audioBuffer) {
    audioSource = new AudioBufferSource({
      codec: isMp4 ? "aac" : "opus",
      bitrate: AUDIO_BITRATE,
    });
    audioTrack = await output.addAudioTrack(audioSource);
  }

  output.start();

  // CanvasSource.add() 接收秒，不是微秒；传错单位会让 MP4 时长膨胀约 1e6 倍。
  const frameDur = 1 / fps;
  if (audioSource) {
    throwIfAborted(opts.signal);
    const audioStart = Number.isFinite(opts.audioStart) ? opts.audioStart : 0;
    const audioEnd = Number.isFinite(opts.audioEnd) ? opts.audioEnd : audioBuffer.duration;
    await audioSource.add(sliceAudioBuffer(audioBuffer, audioStart, audioEnd));
    await audioSource.close?.();
  }

  for (let i = 0; i < n; i++) {
    throwIfAborted(opts.signal);
    renderFrame(ctx, imgs, analysis, frameStart + i, bg, W, H, imageWidth, imageHeight, padding);
    await videoSource.add(i * frameDur, frameDur);
    if (onProgress && (i % 30 === 0 || i === n - 1)) onProgress(i + 1, n);
    if (i % 90 === 0) await new Promise(r => setTimeout(r, 0)); // UI 喘息
  }

  throwIfAborted(opts.signal);
  await output.finalize();
  throwIfAborted(opts.signal);
  return new Blob([output.target.buffer],
    { type: isMp4 ? "video/mp4" : "video/webm" });
}

function throwIfAborted(signal) {
  if (!signal?.aborted) return;
  const error = new Error("导出已停止");
  error.name = "AbortError";
  throw error;
}

function sliceAudioBuffer(audioBuffer, start, end) {
  const sr = audioBuffer.sampleRate;
  const startFrame = Math.max(0, Math.min(audioBuffer.length - 1, Math.floor(start * sr)));
  const endFrame = Math.max(startFrame + 1, Math.min(audioBuffer.length, Math.ceil(end * sr)));
  if (startFrame === 0 && endFrame === audioBuffer.length) return audioBuffer;

  const clipped = new AudioBuffer({
    numberOfChannels: audioBuffer.numberOfChannels,
    length: endFrame - startFrame,
    sampleRate: sr,
  });
  for (let channel = 0; channel < audioBuffer.numberOfChannels; channel++) {
    clipped.copyToChannel(
      audioBuffer.getChannelData(channel).subarray(startFrame, endFrame),
      channel,
    );
  }
  return clipped;
}

/** 绘制背景：纯色填充或图片按 cover 方式铺满画布 */
function paintBackground(ctx, bg, W, H) {
  if (bg?.color) {
    ctx.fillStyle = bg.color;
    ctx.fillRect(0, 0, W, H);
  } else if (bg?.image && bg.image.naturalWidth > 0) {
    const s = Math.max(W / bg.image.naturalWidth, H / bg.image.naturalHeight);
    const w = bg.image.naturalWidth * s, h = bg.image.naturalHeight * s;
    ctx.drawImage(bg.image, (W - w) / 2, (H - h) / 2, w, h);
  }
}

/** 与 app.mjs drawFrame 同构的渲染（无 DOM 依赖）；imageWidth/imageHeight/padding 为 canvasLayout 输出，未传时回退按画布 cover 缩放 */
export function renderFrame(ctx, imgs, analysis, f, bg, W, H, imageWidth, imageHeight, padding) {
  const A = analysis;
  ctx.clearRect(0, 0, W, H);
  paintBackground(ctx, bg, W, H);
  const talking = A.mouth[f] === 1;
  const blinking = A.blink[f] === 1;
  let img = imgs.a;
  if (blinking) {
    if (talking && imgs.d) img = imgs.d;
    else if (!talking && imgs.c) img = imgs.c;
  } else if (talking) img = imgs.b;

  let sx = 1, sy = 1, rot = 0;
  if (A.bounce) { sx = A.bounce.sx[f] || 1; sy = A.bounce.sy[f] || 1; }
  if (A.wiggle) { rot = A.wiggle[f] || 0; }

  if (img) {
    const hasLayout = imageWidth > 0 && imageHeight > 0 && padding >= 0;
    const s = hasLayout ? 1 : Math.min(W / img.naturalWidth, H / img.naturalHeight);
    const w = hasLayout ? imageWidth : img.naturalWidth * s;
    const h = hasLayout ? imageHeight : img.naturalHeight * s;
    ctx.save();
    ctx.translate(W / 2, hasLayout ? padding + imageHeight : H);
    ctx.rotate(rot * Math.PI / 180);
    ctx.scale(sx, sy);
    ctx.drawImage(img, -w / 2, -h, w, h);
    ctx.restore();
  }
}
